### ISSUE TITLE
Matching SPI 2018 Election

### ISSUE THREAD

**Issue by sfrost** [RhodiumToad/sql_stv#1]
Trying to get this to match the 2018 SPI election.

> http://www.spi-inc.org/corporate/votes/2018-board-election/results/

election_id,election_name,num_vacancies
1,SPI 2016 Election,6
2,SPI 2018 Election,3

election_id,candidate_id,candidate_name,precast_lots
2,1,R. Tyler Croy,"{0.701329628936946,0.815147670917213,0.349627710413188,0.320674903225154,0.311302397400141}"
2,2,Luca Filipozzi,"{0.281507593113929,0.378194173797965,0.115456007886678,0.796681656502187,0.926834743004292}"
2,3,Stephen Frost,"{0.0807279809378088,0.20468215784058,0.584207383450121,0.392257483676076,0.676122695207596}"
2,4,Michael Schultheiss,"{0.573151681572199,0.32866288581863,0.768341567832977,0.923960972577333,0.89345313096419}"

id,preference,candidate_id,election_id,voter_id
2074,3,1,2,193
1995,1,2,2,193
2035,2,3,2,193
2112,4,4,2,193
2113,4,1,2,194
1996,1,2,2,194
2075,3,3,2,194
2036,2,4,2,194
2076,3,1,2,195
2037,2,3,2,195
1997,1,4,2,195
2077,3,1,2,196
1998,1,2,2,196
2114,4,3,2,196
2038,2,4,2,196
1999,1,1,2,197
2115,4,2,2,197
2078,3,3,2,197
2039,2,4,2,197
2000,1,2,2,198
2040,2,4,2,198
2079,3,1,2,199
2001,1,3,2,199
2041,2,4,2,199
2116,4,1,2,200
2080,3,2,2,200
2002,1,3,2,200
2042,2,4,2,200
2003,1,1,2,201
2043,2,2,2,201
2081,3,4,2,201
2082,3,1,2,202
2004,1,2,2,202
2044,2,3,2,202
2117,4,4,2,202
2045,2,2,2,203
2083,3,3,2,203
2005,1,4,2,203
2084,3,1,2,204
2046,2,2,2,204
2118,4,3,2,204
2006,1,4,2,204
2047,2,1,2,205
2007,1,3,2,205
2085,3,4,2,205
2048,2,1,2,206
2086,3,2,2,206
2119,4,3,2,206
2008,1,4,2,206
2120,4,1,2,207
2009,1,2,2,207
2087,3,3,2,207
2049,2,4,2,207
2088,3,1,2,208
2050,2,2,2,208
2010,1,4,2,208
2089,3,1,2,209
2051,2,2,2,209
2121,4,3,2,209
2011,1,4,2,209
2090,3,1,2,210
2052,2,2,2,210
2122,4,3,2,210
2012,1,4,2,210
2053,2,1,2,211
2013,1,2,2,211
2091,3,3,2,211
2123,4,4,2,211
2092,3,1,2,212
2014,1,2,2,212
2054,2,3,2,212
2124,4,1,2,213
2093,3,2,2,213
2015,1,3,2,213
2055,2,4,2,213
2094,3,1,2,214
2056,2,2,2,214
2125,4,3,2,214
2016,1,4,2,214
2126,4,1,2,215
2017,1,2,2,215
2057,2,3,2,215
2095,3,4,2,215
2127,4,1,2,216
2058,2,2,2,216
2096,3,3,2,216
2018,1,4,2,216
2059,2,1,2,217
2019,1,2,2,217
2128,4,3,2,217
2097,3,4,2,217
2020,1,1,2,218
2060,2,1,2,219
2021,1,2,2,219
2098,3,3,2,219
2129,4,4,2,219
2061,2,1,2,220
2099,3,2,2,220
2130,4,3,2,220
2022,1,4,2,220
2062,2,1,2,221
2023,1,2,2,221
2100,3,3,2,221
2131,4,4,2,221
2063,2,1,2,222
2024,1,2,2,222
2101,3,3,2,222
2102,3,1,2,223
2064,2,2,2,223
2132,4,3,2,223
2025,1,4,2,223
2065,2,1,2,224
2026,1,2,2,224
2133,4,3,2,224
2103,3,4,2,224
2134,4,1,2,225
2104,3,2,2,225
2066,2,3,2,225
2027,1,4,2,225
2067,2,2,2,226
2028,1,3,2,226
2105,3,4,2,226
2135,4,1,2,227
2029,1,2,2,227
2106,3,3,2,227
2068,2,4,2,227
2136,4,1,2,228
2030,1,2,2,228
2107,3,3,2,228
2069,2,4,2,228
2031,1,1,2,229
2108,3,2,2,229
2070,2,3,2,229
2137,4,4,2,229
2138,4,1,2,230
2032,1,2,2,230
2071,2,3,2,230
2109,3,4,2,230
2110,3,1,2,231
2072,2,2,2,231
2033,1,4,2,231
2139,4,1,2,232
2111,3,2,2,232
2073,2,3,2,232
2034,1,4,2,232

**Comment by RhodiumToad** [comment]
Yeah, my interpretation of the rules was apparently wrong, so I've fixed it to use theirs instead; the result now matches theirs even down to the intermediate count totals.
